version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9000:9000"  # Porta de acesso ao MinIO Console
      - "9001:9001"  # Porta de acesso ao MinIO Console Web
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data:
    driver: local
